/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Remote interface for ArticleFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ArticleFacade
   extends javax.ejb.EJBObject
{

   public ezbay.model.interfaces.ArticleDTO createArticle( ezbay.model.interfaces.ArticleDTO articleDTO,ezbay.model.interfaces.VendeurDTO vendeurDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateArticle( ezbay.model.interfaces.ArticleDTO articleDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeArticle( ezbay.model.interfaces.ArticleDTO articleDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public ezbay.model.interfaces.ArticleDTO getArticle( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public ezbay.model.interfaces.VendeurDTO getVendeurDTO( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public ezbay.model.interfaces.CategorieDTO getCategorieDTO( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getArticles(  )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByLibelle( java.lang.String libelle )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByVendeur( java.lang.String vendeurId )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByCategorie( java.lang.String categorieId )
      throws java.rmi.RemoteException;

}
