/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Local home interface for ClientFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ClientFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ClientFacadeLocal";
   public static final String JNDI_NAME="ClientFacadeLocal";

   public ezbay.model.interfaces.ClientFacadeLocal create()
      throws javax.ejb.CreateException;

}
