/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Remote interface for MembreFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreFacade
   extends javax.ejb.EJBObject
{

   public ezbay.model.interfaces.MembreDTO createMembre( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void updateMembre( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeMembre( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createClient( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createVendeur( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeVendeur( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeClient( ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

}
