/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Home interface for MembreFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MembreFacade";
   public static final String JNDI_NAME="ejb/MembreFacade";

   public ezbay.model.interfaces.MembreFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
