/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Local interface for Membre.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getId(  ) ;

   public void setId( java.lang.String id ) ;

   public java.lang.String getNom(  ) ;

   public void setNom( java.lang.String nom ) ;

   public ezbay.model.interfaces.VendeurLocal getVendeurLocal(  ) ;

   public void setVendeurLocal( ezbay.model.interfaces.VendeurLocal vendeurLocal ) ;

   public ezbay.model.interfaces.ClientLocal getClientLocal(  ) ;

   public void setClientLocal( ezbay.model.interfaces.ClientLocal clientLocal ) ;

   public ezbay.model.interfaces.MembreDTO getMembreDTO(  ) ;

   public void updateMembre( ezbay.model.interfaces.MembreDTO membreDTO ) throws java.lang.Exception;

}
