/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Local interface for VendeurFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public ezbay.model.interfaces.VendeurDTO createVendeur(  ) throws java.lang.Exception;

   public void removeVendeur( ezbay.model.interfaces.VendeurDTO vendeurDTO ) throws java.lang.Exception;

   public ezbay.model.interfaces.VendeurDTO getVendeur( java.lang.String vendeurId ) throws java.lang.Exception;

   public java.util.Collection getVendeurs(  ) ;

   public java.util.Collection getArticles( ezbay.model.interfaces.VendeurDTO vendeurDTO ) ;

}
