/*
 * Generated by XDoclet - Do not edit!
 */
package ezbay.model.interfaces;

/**
 * Local home interface for Vendeur.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VendeurLocal";
   public static final String JNDI_NAME="VendeurLocal";

   public ezbay.model.interfaces.VendeurLocal create(ezbay.model.interfaces.VendeurDTO vendeurTO)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByNom(java.lang.String nom)
      throws javax.ejb.FinderException;

   public ezbay.model.interfaces.VendeurLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
