/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.ejb;

/**
 * CMP layer for ActionTransaction.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class ActionTransactionCMP
   extends axlomoso.ezbay.model.ejb.ActionTransactionBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(axlomoso.ezbay.model.interfaces.ActionTransactionDTO transactionDTO)
    */
   public void ejbPostCreate(axlomoso.ezbay.model.interfaces.ActionTransactionDTO transactionDTO)
   {
   }

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

      ActionTransactionDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private axlomoso.ezbay.model.interfaces.ActionTransactionDTO ActionTransactionDTO = null;

   public axlomoso.ezbay.model.interfaces.ActionTransactionDTO getActionTransactionDTO()
   {
      ActionTransactionDTO = new axlomoso.ezbay.model.interfaces.ActionTransactionDTO();
      try
         {
            ActionTransactionDTO.setId( getId() );
            ActionTransactionDTO.setDate( getDate() );
            ActionTransactionDTO.setMontant( getMontant() );
            ActionTransactionDTO.setAvis( getAvis() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return ActionTransactionDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.util.Date getDate() ;

   public abstract void setDate( java.util.Date date ) ;

   public abstract java.lang.Double getMontant() ;

   public abstract void setMontant( java.lang.Double montant ) ;

   public abstract java.lang.String getAvis() ;

   public abstract void setAvis( java.lang.String avis ) ;

}
