/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.ejb;

/**
 * CMP layer for Article.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class ArticleCMP
   extends axlomoso.ezbay.model.ejb.ArticleBean
   implements javax.ejb.EntityBean
{

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

      ArticleDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private axlomoso.ezbay.model.interfaces.ArticleDTO ArticleDTO = null;

   public axlomoso.ezbay.model.interfaces.ArticleDTO getArticleDTO()
   {
      ArticleDTO = new axlomoso.ezbay.model.interfaces.ArticleDTO();
      try
         {
            ArticleDTO.setId( getId() );
            ArticleDTO.setEnVente( getEnVente() );
            ArticleDTO.setLibelle( getLibelle() );
            ArticleDTO.setMarque( getMarque() );
            ArticleDTO.setModele( getModele() );
            ArticleDTO.setPrixVente( getPrixVente() );
            ArticleDTO.setAnneeFabrication( getAnneeFabrication() );
            ArticleDTO.setDescription( getDescription() );
            ArticleDTO.setDateLimite( getDateLimite() );
            ArticleDTO.setVendeurPseudo( getVendeurPseudo() );
            ArticleDTO.setVendeurMembreId( getVendeurMembreId() );
            ArticleDTO.setVendeurId( getVendeurId() );
            ArticleDTO.setEncherisseurPseudo( getEncherisseurPseudo() );
            ArticleDTO.setEncherisseurMembreId( getEncherisseurMembreId() );
            ArticleDTO.setEncherisseurClientId( getEncherisseurClientId() );
            ArticleDTO.setDerniereEnchereDate( getDerniereEnchereDate() );
            ArticleDTO.setDerniereEnchereMontant( getDerniereEnchereMontant() );
            ArticleDTO.setNbEncheres( getNbEncheres() );
            ArticleDTO.setAcheteurPseudo( getAcheteurPseudo() );
            ArticleDTO.setAcheteurId( getAcheteurId() );
            ArticleDTO.setTransactionDate( getTransactionDate() );
            ArticleDTO.setTransactionMontant( getTransactionMontant() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return ArticleDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.lang.Boolean getEnVente() ;

   public abstract void setEnVente( java.lang.Boolean enVente ) ;

   public abstract java.lang.String getLibelle() ;

   public abstract void setLibelle( java.lang.String libelle ) ;

   public abstract java.lang.String getMarque() ;

   public abstract void setMarque( java.lang.String marque ) ;

   public abstract java.lang.String getModele() ;

   public abstract void setModele( java.lang.String modele ) ;

   public abstract java.lang.Double getPrixVente() ;

   public abstract void setPrixVente( java.lang.Double prixVente ) ;

   public abstract java.lang.Integer getAnneeFabrication() ;

   public abstract void setAnneeFabrication( java.lang.Integer anneeFabrication ) ;

   public abstract java.lang.String getDescription() ;

   public abstract void setDescription( java.lang.String description ) ;

   public abstract java.util.Date getDateLimite() ;

   public abstract void setDateLimite( java.util.Date dateLimite ) ;

   public abstract java.lang.String getVendeurPseudo() ;

   public abstract void setVendeurPseudo( java.lang.String vendeurPseudo ) ;

   public abstract java.lang.String getVendeurMembreId() ;

   public abstract void setVendeurMembreId( java.lang.String vendeurMembreId ) ;

   public abstract java.lang.String getVendeurId() ;

   public abstract void setVendeurId( java.lang.String vendeurId ) ;

   public abstract java.lang.String getEncherisseurPseudo() ;

   public abstract void setEncherisseurPseudo( java.lang.String encherisseurPseudo ) ;

   public abstract java.lang.String getEncherisseurMembreId() ;

   public abstract void setEncherisseurMembreId( java.lang.String encherisseurMembreId ) ;

   public abstract java.lang.String getEncherisseurClientId() ;

   public abstract void setEncherisseurClientId( java.lang.String encherisseurClientId ) ;

   public abstract java.util.Date getDerniereEnchereDate() ;

   public abstract void setDerniereEnchereDate( java.util.Date derniereEnchereDate ) ;

   public abstract java.lang.Double getDerniereEnchereMontant() ;

   public abstract void setDerniereEnchereMontant( java.lang.Double derniereEnchereMontant ) ;

   public abstract java.lang.Integer getNbEncheres() ;

   public abstract void setNbEncheres( java.lang.Integer nbEncheres ) ;

   public abstract java.lang.String getAcheteurPseudo() ;

   public abstract void setAcheteurPseudo( java.lang.String acheteurPseudo ) ;

   public abstract java.lang.String getAcheteurId() ;

   public abstract void setAcheteurId( java.lang.String acheteurId ) ;

   public abstract java.util.Date getTransactionDate() ;

   public abstract void setTransactionDate( java.util.Date transactionDate ) ;

   public abstract java.lang.Double getTransactionMontant() ;

   public abstract void setTransactionMontant( java.lang.Double transactionMontant ) ;

}
