/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.ejb;

/**
 * CMP layer for Article.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class ArticleCMP
   extends axlomoso.ezbay.model.ejb.ArticleBean
   implements javax.ejb.EntityBean
{

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

      ArticleDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private axlomoso.ezbay.model.interfaces.ArticleDTO ArticleDTO = null;

   public axlomoso.ezbay.model.interfaces.ArticleDTO getArticleDTO()
   {
      ArticleDTO = new axlomoso.ezbay.model.interfaces.ArticleDTO();
      try
         {
            ArticleDTO.setId( getId() );
            ArticleDTO.setLibelle( getLibelle() );
            ArticleDTO.setMarque( getMarque() );
            ArticleDTO.setModele( getModele() );
            ArticleDTO.setPrixVente( getPrixVente() );
            ArticleDTO.setAnneeFabrication( getAnneeFabrication() );
            ArticleDTO.setDescription( getDescription() );
            ArticleDTO.setDateLimite( getDateLimite() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return ArticleDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.lang.String getLibelle() ;

   public abstract void setLibelle( java.lang.String libelle ) ;

   public abstract java.lang.String getMarque() ;

   public abstract void setMarque( java.lang.String marque ) ;

   public abstract java.lang.String getModele() ;

   public abstract void setModele( java.lang.String modele ) ;

   public abstract java.lang.Double getPrixVente() ;

   public abstract void setPrixVente( java.lang.Double prixVente ) ;

   public abstract java.lang.Integer getAnneeFabrication() ;

   public abstract void setAnneeFabrication( java.lang.Integer anneeFabrication ) ;

   public abstract java.lang.String getDescription() ;

   public abstract void setDescription( java.lang.String description ) ;

   public abstract java.util.Date getDateLimite() ;

   public abstract void setDateLimite( java.util.Date dateLimite ) ;

}
