/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.ejb;

/**
 * CMP layer for Categorie.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class CategorieCMP
   extends axlomoso.ezbay.model.ejb.CategorieBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(axlomoso.ezbay.model.interfaces.CategorieDTO categorieDTO)
    */
   public void ejbPostCreate(axlomoso.ezbay.model.interfaces.CategorieDTO categorieDTO)
   {
   }

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

      CategorieDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private axlomoso.ezbay.model.interfaces.CategorieDTO CategorieDTO = null;

   public axlomoso.ezbay.model.interfaces.CategorieDTO getCategorieDTO()
   {
      CategorieDTO = new axlomoso.ezbay.model.interfaces.CategorieDTO();
      try
         {
            CategorieDTO.setId( getId() );
            CategorieDTO.setLibelle( getLibelle() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return CategorieDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.lang.String getLibelle() ;

   public abstract void setLibelle( java.lang.String libelle ) ;

}
