/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.ejb;

/**
 * CMP layer for Membre.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class MembreCMP
   extends axlomoso.ezbay.model.ejb.MembreBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(axlomoso.ezbay.model.interfaces.MembreDTO membreDTO)
    */
   public void ejbPostCreate(axlomoso.ezbay.model.interfaces.MembreDTO membreDTO)
   {
   }

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

      MembreDTO = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

   private axlomoso.ezbay.model.interfaces.MembreDTO MembreDTO = null;

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembreDTO()
   {
      MembreDTO = new axlomoso.ezbay.model.interfaces.MembreDTO();
      try
         {
            MembreDTO.setId( getId() );
            MembreDTO.setNom( getNom() );
            MembreDTO.setPrenom( getPrenom() );
            MembreDTO.setPseudo( getPseudo() );
            MembreDTO.setPassword( getPassword() );
            MembreDTO.setEmail( getEmail() );
            MembreDTO.setAdresse( getAdresse() );
            MembreDTO.setCodePostal( getCodePostal() );
            MembreDTO.setVille( getVille() );
            MembreDTO.setPays( getPays() );
            MembreDTO.setTelephoneFixe( getTelephoneFixe() );
            MembreDTO.setTelephonePortable( getTelephonePortable() );
            MembreDTO.setDateNaissance( getDateNaissance() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return MembreDTO;
   }

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.lang.String getNom() ;

   public abstract void setNom( java.lang.String nom ) ;

   public abstract java.lang.String getPrenom() ;

   public abstract void setPrenom( java.lang.String prenom ) ;

   public abstract java.lang.String getPseudo() ;

   public abstract void setPseudo( java.lang.String pseudo ) ;

   public abstract java.lang.String getPassword() ;

   public abstract void setPassword( java.lang.String password ) ;

   public abstract java.lang.String getEmail() ;

   public abstract void setEmail( java.lang.String email ) ;

   public abstract java.lang.String getAdresse() ;

   public abstract void setAdresse( java.lang.String adresse ) ;

   public abstract java.lang.String getCodePostal() ;

   public abstract void setCodePostal( java.lang.String codePostal ) ;

   public abstract java.lang.String getVille() ;

   public abstract void setVille( java.lang.String ville ) ;

   public abstract java.lang.String getPays() ;

   public abstract void setPays( java.lang.String pays ) ;

   public abstract java.lang.String getTelephoneFixe() ;

   public abstract void setTelephoneFixe( java.lang.String telephoneFixe ) ;

   public abstract java.lang.String getTelephonePortable() ;

   public abstract void setTelephonePortable( java.lang.String telephonePortable ) ;

   public abstract java.util.Date getDateNaissance() ;

   public abstract void setDateNaissance( java.util.Date dateNaissance ) ;

}
