/*
 * Generated by XDoclet - Do not edit!
 */
package de.laliluna.tutorial.simpleBean.ejb;

/**
 * CMP layer for SimpleBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public abstract class SimpleBeanCMP
   extends de.laliluna.tutorial.simpleBean.ejb.SimpleBean
   implements javax.ejb.EntityBean
{

   public de.laliluna.tutorial.simpleBean.interfaces.SimpleBeanData getData()
   {
      de.laliluna.tutorial.simpleBean.interfaces.SimpleBeanData dataHolder = null;
      try
      {
         dataHolder = new de.laliluna.tutorial.simpleBean.interfaces.SimpleBeanData();

         dataHolder.setId( getId() );
         dataHolder.setName( getName() );

      }
      catch (RuntimeException e)
      {
         throw new javax.ejb.EJBException(e);
      }

      return dataHolder;
   }

   public void ejbLoad() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbLoad();
   }

   public void ejbStore() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
         super.ejbStore();
   }

   public void ejbActivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbActivate();
   }

   public void ejbPassivate() throws javax.ejb.EJBException, java.rmi.RemoteException
   {
      super.ejbPassivate();

   }

   public void setEntityContext(javax.ejb.EntityContext ctx) throws javax.ejb.EJBException
   {
      super.setEntityContext(ctx);
   }

   public void unsetEntityContext() throws javax.ejb.EJBException
   {
      super.unsetEntityContext();
   }

   public void ejbRemove() throws javax.ejb.EJBException, java.rmi.RemoteException, javax.ejb.RemoveException
   {
      super.ejbRemove();

   }

 /* Value Objects BEGIN */

/* Value Objects END */

   public abstract java.lang.String getId() ;

   public abstract void setId( java.lang.String id ) ;

   public abstract java.lang.String getName() ;

   public abstract void setName( java.lang.String name ) ;

}
