/*
 * Generated by XDoclet - Do not edit!
 */
package de.laliluna.tutorial.simpleBean.interfaces;

/**
 * Local home interface for SimpleBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SimpleBeanLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SimpleBeanLocal";
   public static final String JNDI_NAME="ejb/SimpleBeanLocalHome";

   public de.laliluna.tutorial.simpleBean.interfaces.SimpleBeanLocal create()
      throws javax.ejb.CreateException;

   public de.laliluna.tutorial.simpleBean.interfaces.SimpleBeanLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
