/*
 * Generated by XDoclet - Do not edit!
 */
package de.laliluna.tutorial.simpleBean.interfaces;

/**
 * Home interface for SimpleBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SimpleBeanHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/SimpleBean";
   public static final String JNDI_NAME="ejb/SimpleBeanHome";

   public de.laliluna.tutorial.simpleBean.interfaces.SimpleBean create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public de.laliluna.tutorial.simpleBean.interfaces.SimpleBean findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
