/*
 * Generated by XDoclet - Do not edit!
 */
package de.laliluna.tutorial.simpleBean.interfaces;

/**
 * Local interface for SimpleBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SimpleBeanLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getId(  ) ;

   public void setId( java.lang.String id ) ;

   public java.lang.String getName(  ) ;

   public void setName( java.lang.String name ) ;

}
