/*
 * Generated by XDoclet - Do not edit!
 */
package de.laliluna.tutorial.simpleBean.interfaces;

/**
 * Remote interface for SimpleBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface SimpleBean
   extends javax.ejb.EJBObject
{

   public java.lang.String getId(  )
      throws java.rmi.RemoteException;

   public void setId( java.lang.String id )
      throws java.rmi.RemoteException;

   public java.lang.String getName(  )
      throws java.rmi.RemoteException;

   public void setName( java.lang.String name )
      throws java.rmi.RemoteException;

}
