/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for ActionTransactionFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionTransactionFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ActionTransactionFacadeLocal";
   public static final String JNDI_NAME="ActionTransactionFacadeLocal";

   public axlomoso.ezbay.model.interfaces.ActionTransactionFacadeLocal create()
      throws javax.ejb.CreateException;

}
