/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for ActionEnchereFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.ActionEnchereDTO createActionEnchere( axlomoso.ezbay.model.interfaces.ActionEnchereDTO enchereDTO,axlomoso.ezbay.model.interfaces.ArticleLocal articleLocal,axlomoso.ezbay.model.interfaces.ClientLocal clientLocal )
      throws javax.ejb.CreateException, java.rmi.RemoteException;

   public java.util.Collection getActionEncheresByArticle( java.lang.String articleId )
      throws java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.ClientDTO getEncherisseur( java.lang.String enchereId )
      throws java.rmi.RemoteException;

}
