/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for ActionEnchereFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereFacade
   extends javax.ejb.EJBObject
{

   public java.util.Collection getActionEncheresByArticle( java.lang.String articleId )
      throws java.rmi.RemoteException;

}
