/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for ActionEnchereFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public java.util.Collection getActionEncheresByArticle( java.lang.String articleId ) ;

}
