/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for ActionTransactionFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionTransactionFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.ActionTransactionDTO createActionTransaction( axlomoso.ezbay.model.interfaces.ActionTransactionDTO transactionDTO,axlomoso.ezbay.model.interfaces.ArticleLocal articleLocal,axlomoso.ezbay.model.interfaces.ClientLocal clientLocal )
      throws javax.ejb.CreateException, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.ActionTransactionDTO getActionTransactionByArticle( java.lang.String articleId )
      throws java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.ClientDTO getAcquereur( java.lang.String articleId )
      throws java.rmi.RemoteException;

}
