/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Value object for ActionTransaction.
 *
 * Notice, this object is used to represent the state of an 
 * ActionTransaction object. This value object
 * Is not connected to the database in any way, it is just a normal object used 
 * as a container for data from an EJB. 
 *
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class ActionTransactionDTO
   extends java.lang.Object
   implements java.io.Serializable, java.lang.Cloneable 
{

   private java.lang.String id;
   private boolean idHasBeenSet = false;

   private java.util.Date date;
   private boolean dateHasBeenSet = false;

   private java.lang.Double montant;
   private boolean montantHasBeenSet = false;

   private java.lang.String primaryKey;

   public ActionTransactionDTO()
   {
   }

   public ActionTransactionDTO( java.lang.String id,java.util.Date date,java.lang.Double montant )
   {
       setId(id);
       setDate(date);
       setMontant(montant);
	   primaryKey = this.getId();
   }

   /**
    * @deprecated use {@link #clone}
    */
   public ActionTransactionDTO( ActionTransactionDTO otherValue )
   {
	  this.id = otherValue.id;
	  idHasBeenSet = true;
	  this.date = otherValue.date;
	  dateHasBeenSet = true;
	  this.montant = otherValue.montant;
	  montantHasBeenSet = true;

	  primaryKey = this.getId();
   }

   public java.lang.String getPrimaryKey()
   {
	  return primaryKey;
   }

   public void setPrimaryKey( java.lang.String primaryKey)
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.primaryKey = primaryKey;
	  setId( primaryKey );
   }

   public java.lang.String getId()
   {
	  return this.id;
   }

   public void setId( java.lang.String id )
   {
	  this.id = id;
	  idHasBeenSet = true;

      primaryKey = id;
   }

   public boolean idHasBeenSet(){
	  return idHasBeenSet;
   }
   public java.util.Date getDate()
   {
	  return this.date;
   }

   public void setDate( java.util.Date date )
   {
	  this.date = date;
	  dateHasBeenSet = true;

   }

   public boolean dateHasBeenSet(){
	  return dateHasBeenSet;
   }
   public java.lang.Double getMontant()
   {
	  return this.montant;
   }

   public void setMontant( java.lang.Double montant )
   {
	  this.montant = montant;
	  montantHasBeenSet = true;

   }

   public boolean montantHasBeenSet(){
	  return montantHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("id=" + getId() + " " + "date=" + getDate() + " " + "montant=" + getMontant());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return idHasBeenSet;
   }

   /**
    *
    * @deprecated use {@link #equals}
    */
   public boolean isIdentical(Object other)
   {
          if (other instanceof ActionTransactionDTO)
          {
                 ActionTransactionDTO that = (ActionTransactionDTO) other;
                 boolean lEquals = true;
                 if( this.id == null )
                 {
                        lEquals = lEquals && ( that.id == null );
                 }
                 else
                 {
                        lEquals = lEquals && this.id.equals( that.id );
                 }
                 if( this.date == null )
                 {
                        lEquals = lEquals && ( that.date == null );
                 }
                 else
                 {
                        lEquals = lEquals && this.date.equals( that.date );
                 }
                 if( this.montant == null )
                 {
                        lEquals = lEquals && ( that.montant == null );
                 }
                 else
                 {
                        lEquals = lEquals && this.montant.equals( that.montant );
                 }

                 return lEquals;
          }
          else
          {
                 return false;
          }
   }

    public boolean equals(Object other) {

        //If it's not the correct type, clearly it isn't equal to this.
        if (!(other instanceof ActionTransactionDTO)) { 
            return false;
        }

        return equals((ActionTransactionDTO) other);
    }

    /**
     * This class is not using strict ordering. This means that the object is not Comparable, and
     * each check for equality will test all members for equality. We do not check collections for
     * equality however, so you would be wise to not use this if you have collection typed EJB References.
     */
    public boolean equals(ActionTransactionDTO that) {

        //try to get lucky.
        if (this == that) {
            return true;
        }
        //this clearly isn't null.
        if(null == that) {
            return false;
        }

        if(this.id != that.id) {

            if( this.id == null || that.id == null ) {
                return false;
            }

            if(!this.id.equals(that.id)) {
                return false;
            }

        }

        if(this.date != that.date) {

            if( this.date == null || that.date == null ) {
                return false;
            }

            if(!this.date.equals(that.date)) {
                return false;
            }

        }

        if(this.montant != that.montant) {

            if( this.montant == null || that.montant == null ) {
                return false;
            }

            if(!this.montant.equals(that.montant)) {
                return false;
            }

        }

        return true;

    }

    public Object clone() throws java.lang.CloneNotSupportedException {
        ActionTransactionDTO other = (ActionTransactionDTO) super.clone();

        return other;
    }

    public ReadOnlyActionTransactionDTO getReadOnlyActionTransactionDTO() {
        return new ReadOnlyActionTransactionDTO();
    }

    public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.id != null) ? this.id.hashCode() : 0);

      result = 37*result + ((this.date != null) ? this.date.hashCode() : 0);

      result = 37*result + ((this.montant != null) ? this.montant.hashCode() : 0);

	  return result;
    }

    /**
     * Covariant function so the compiler can choose the proper one at compile time,
     * eliminates the need for XDoclet to really understand compiletime typing.
     *
     * Read only collections need to be synchronized. Once we start giving out handles
     * to these collections, they'll be used in other threads sooner or later. 
     */
    private static java.util.Collection wrapCollection(java.util.Collection input) {
        return java.util.Collections.synchronizedCollection(input);
    }
    /**
     * Covariant function so the compiler can choose the proper one at compile time,
     * eliminates the need for XDoclet to really understand compiletime typing.
     *
     * Read only collections need to be synchronized. Once we start giving out handles
     * to these collections, they'll be used in other threads sooner or later. 
     */
    private static java.util.Set wrapCollection(java.util.Set input) {
        return java.util.Collections.synchronizedSet(input);
    }
    /**
     * Covariant function. This is used in covariant form so that the compiler
     * can do some of our conditional branches for us. If I made these functions
     * have different names, then XDoclet would have to choose between them based on 
     * compiletime types, that wouldn't be easy. 
     */
    private static java.util.Collection wrapReadOnly(java.util.Collection input) {
        return java.util.Collections.unmodifiableCollection(input);
    }
    /**
     * Covariant function. This is used in covariant form so that the compiler
     * can do some of our conditional branches for us. If I made these functions
     * have different names, then XDoclet would have to choose between them based on 
     * compiletime types, that wouldn't be easy. 
     */
    private static java.util.Set wrapReadOnly(java.util.Set input) {
        return java.util.Collections.unmodifiableSet(input);
    }

    private final class ReadOnlyActionTransactionDTO 
    implements java.lang.Cloneable, java.io.Serializable 
    {
        private ActionTransactionDTO underlying() {
            return ActionTransactionDTO.this;
        }

       public java.lang.String getId() {
              return underlying().id;
       }

       public java.util.Date getDate() {
              return underlying().date;
       }

       public java.lang.Double getMontant() {
              return underlying().montant;
       }

        public int hashCode() {
            return 101 * underlying().hashCode();
        }

        public boolean equals(Object o) {
            if(o instanceof ReadOnlyActionTransactionDTO) {
                return this.equals((ReadOnlyActionTransactionDTO) o);
            }
            return false;
        }

        public boolean equals(ReadOnlyActionTransactionDTO that) {
            if(null == that) {
                return false;
            }

            return this.underlying().equals(that.underlying());
        }

    }

}
