/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Home interface for ActionTransactionFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionTransactionFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ActionTransactionFacade";
   public static final String JNDI_NAME="ejb/ActionTransactioneFacade";

   public axlomoso.ezbay.model.interfaces.ActionTransactionFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
