/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for ActionEnchereFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public axlomoso.ezbay.model.interfaces.ActionEnchereDTO createActionEnchere( axlomoso.ezbay.model.interfaces.ActionEnchereDTO enchereDTO,axlomoso.ezbay.model.interfaces.ArticleLocal articleLocal,axlomoso.ezbay.model.interfaces.ClientLocal clientLocal ) throws javax.ejb.CreateException;

   public java.util.Collection getActionEncheresByArticle( java.lang.String articleId ) ;

   public axlomoso.ezbay.model.interfaces.ClientDTO getEncherisseur( java.lang.String enchereId ) ;

}
