/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for ActionTransactionFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionTransactionFacade
   extends javax.ejb.EJBObject
{

   public void setAvis( java.lang.String transactionId,java.lang.String avis )
      throws java.rmi.RemoteException;

}
