/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for ActionEnchere.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ActionEnchereLocal";
   public static final String JNDI_NAME="ActionEnchereLocal";

   public axlomoso.ezbay.model.interfaces.ActionEnchereLocal create(axlomoso.ezbay.model.interfaces.ActionEnchereDTO enchereDTO , axlomoso.ezbay.model.interfaces.ArticleLocal articleLocal , axlomoso.ezbay.model.interfaces.ClientLocal clientLocal)
      throws javax.ejb.CreateException;

   public java.util.Collection findByArticleId(java.lang.String articleId)
      throws javax.ejb.FinderException;

   public axlomoso.ezbay.model.interfaces.ActionEnchereLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
