/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for ActionEnchereFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ActionEnchereFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ActionEnchereFacadeLocal";
   public static final String JNDI_NAME="ActionEnchereFacadeLocal";

   public axlomoso.ezbay.model.interfaces.ActionEnchereFacadeLocal create()
      throws javax.ejb.CreateException;

}
