/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Home interface for ArticleFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ArticleFacadeHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ArticleFacade";
   public static final String JNDI_NAME="ejb/ArticleFacade";

   public axlomoso.ezbay.model.interfaces.ArticleFacade create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
