/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for ArticleFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ArticleFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.ArticleDTO getArticle( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.VendeurDTO getVendeurDTO( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.CategorieDTO getCategorieDTO( java.lang.String articleId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getArticles(  )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticles( java.lang.String libcategorie,java.lang.String libelle,java.lang.String marque,java.lang.String modele,java.lang.Double prixVente,java.lang.Integer anneeFabrication,java.util.Date dateLimite )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByLibelle( java.lang.String libelle )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByVendeur( java.lang.String vendeurId )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticlesByCategorie( java.lang.String categorieId )
      throws java.rmi.RemoteException;

}
