/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Article.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ArticleLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ArticleLocal";
   public static final String JNDI_NAME="ArticleLocal";

   public axlomoso.ezbay.model.interfaces.ArticleLocal create(axlomoso.ezbay.model.interfaces.ArticleDTO articleTO , axlomoso.ezbay.model.interfaces.VendeurLocal vendeur)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByLibelle(java.lang.String libelle)
      throws javax.ejb.FinderException;

   public java.util.Collection findByMarque(java.lang.String marque)
      throws javax.ejb.FinderException;

   public java.util.Collection findByModele(java.lang.String modele)
      throws javax.ejb.FinderException;

   public java.util.Collection findByPrixVente(java.lang.Double prixVente)
      throws javax.ejb.FinderException;

   public java.util.Collection findByAnneeFabrication(java.lang.Integer anneeFabrication)
      throws javax.ejb.FinderException;

   public java.util.Collection findByDateLimite(java.util.Date dateLimite)
      throws javax.ejb.FinderException;

   public java.util.Collection findByDescription(java.lang.String description)
      throws javax.ejb.FinderException;

   public axlomoso.ezbay.model.interfaces.ArticleLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
