/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Categorie.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CategorieLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CategorieLocal";
   public static final String JNDI_NAME="CategorieLocal";

   public axlomoso.ezbay.model.interfaces.CategorieLocal create(axlomoso.ezbay.model.interfaces.CategorieDTO categorieDTO)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByLibelle(java.lang.String libelle)
      throws javax.ejb.FinderException;

   public axlomoso.ezbay.model.interfaces.CategorieLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
