/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for CategorieFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CategorieFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.CategorieDTO createCategorie( axlomoso.ezbay.model.interfaces.CategorieDTO categorieDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeCategorie( axlomoso.ezbay.model.interfaces.CategorieDTO categorieDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.CategorieDTO getCategorie( java.lang.String categorieId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getArticlesDTO( java.lang.String categorieId )
      throws java.lang.Exception, java.rmi.RemoteException;

}
