/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for Categorie.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CategorieLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getId(  ) ;

   public void setId( java.lang.String id ) ;

   public java.lang.String getLibelle(  ) ;

   public void setLibelle( java.lang.String libelle ) ;

   public java.util.Collection getArticleLocal(  ) ;

   public void setArticleLocal( axlomoso.ezbay.model.interfaces.ArticleLocal articleLocal ) ;

   public axlomoso.ezbay.model.interfaces.CategorieDTO getCategorieDTO(  ) ;

}
