/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for CategorieFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface CategorieFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CategorieFacadeLocal";
   public static final String JNDI_NAME="CategorieFacadeLocal";

   public axlomoso.ezbay.model.interfaces.CategorieFacadeLocal create()
      throws javax.ejb.CreateException;

}
