/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for ClientFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ClientFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public axlomoso.ezbay.model.interfaces.ClientDTO createClient(  ) throws java.lang.Exception;

}
