/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Client.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ClientLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/ClientLocal";
   public static final String JNDI_NAME="ClientLocal";

   public axlomoso.ezbay.model.interfaces.ClientLocal create()
      throws javax.ejb.CreateException;

   public axlomoso.ezbay.model.interfaces.ClientLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
