/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for ClientFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface ClientFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public axlomoso.ezbay.model.interfaces.ClientDTO createClient(  ) throws java.lang.Exception;

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembre( java.lang.String clientId ) throws java.lang.Exception;

   public java.util.Collection getArticlesEnEncheres( java.lang.String clientId ) ;

   public java.util.Collection getArticlesAchetes( java.lang.String clientId ) ;

}
