/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Enchere.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface EnchereLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/EnchereLocal";
   public static final String JNDI_NAME="EnchereLocal";

   public axlomoso.ezbay.model.interfaces.EnchereLocal create(axlomoso.ezbay.model.interfaces.ActionEnchereDTO enchereDTO)
      throws javax.ejb.CreateException;

   public axlomoso.ezbay.model.interfaces.EnchereLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
