/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for MembreFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.MembreDTO createMembre( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembre( java.lang.String membreId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembre( java.lang.String pseudo,java.lang.String password )
      throws javax.ejb.FinderException, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.VendeurDTO getVendeurDTO( java.lang.String membreId )
      throws java.rmi.RemoteException;

   public void updateMembre( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeMembre( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createVendeur( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void createClient( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeVendeur( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeClient( axlomoso.ezbay.model.interfaces.MembreDTO membreDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

}
