/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for MembreFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MembreFacadeLocal";
   public static final String JNDI_NAME="MembreFacadeLocal";

   public axlomoso.ezbay.model.interfaces.MembreFacadeLocal create()
      throws javax.ejb.CreateException;

}
