/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Membre.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/MembreLocal";
   public static final String JNDI_NAME="MembreLocal";

   public axlomoso.ezbay.model.interfaces.MembreLocal create(axlomoso.ezbay.model.interfaces.MembreDTO membreDTO)
      throws javax.ejb.CreateException;

   public java.util.Collection findByPseudo(java.lang.String pseudo)
      throws javax.ejb.FinderException;

   public axlomoso.ezbay.model.interfaces.MembreLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
