/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for MembreFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface MembreFacadeLocal
   extends javax.ejb.EJBLocalObject
{

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembre( java.lang.String membreId ) throws java.lang.Exception;

   public axlomoso.ezbay.model.interfaces.MembreDTO getMembre( java.lang.String pseudo,java.lang.String password ) ;

}
