/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for TimerFinVente.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TimerFinVenteLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TimerFinVenteLocal";
   public static final String JNDI_NAME="TimerFinVenteLocal";

   public axlomoso.ezbay.model.interfaces.TimerFinVenteLocal create()
      throws javax.ejb.CreateException;

}
