/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for TimerFinVente.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TimerFinVenteLocal
   extends javax.ejb.EJBLocalObject
{

   public void initializeTimer( long timeout,java.lang.String timerName ) ;

   public void cancelTimer( java.lang.String timerName ) ;

}
