/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for TimerFinVenteBean.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TimerFinVenteBean
   extends javax.ejb.EJBObject
{

   public void initializeTimer( long timeout,java.lang.String timerName )
      throws java.rmi.RemoteException;

   public void cancelTimer( java.lang.String timerName )
      throws java.rmi.RemoteException;

}
