/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for Vendeur.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VendeurLocal";
   public static final String JNDI_NAME="VendeurLocal";

   public axlomoso.ezbay.model.interfaces.VendeurLocal create(axlomoso.ezbay.model.interfaces.VendeurDTO vendeurDTO)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public axlomoso.ezbay.model.interfaces.VendeurLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
