/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for Vendeur.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getId(  ) ;

   public void setId( java.lang.String id ) ;

   public java.util.Collection getArticle(  ) ;

   public void setArticle( java.util.Collection article ) ;

   public axlomoso.ezbay.model.interfaces.MembreLocal getMembreLocal(  ) ;

   public void setMembreLocal( axlomoso.ezbay.model.interfaces.MembreLocal membreLocal ) ;

   public axlomoso.ezbay.model.interfaces.VendeurDTO getVendeurDTO(  ) ;

}
