/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local interface for Vendeur.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurLocal
   extends javax.ejb.EJBLocalObject
{

   public java.lang.String getId(  ) ;

   public void setId( java.lang.String id ) ;

   public java.lang.String getNomProprioCB(  ) ;

   public void setNomProprioCB( java.lang.String nomProprioCB ) ;

   public java.lang.String getNumCB(  ) ;

   public void setNumCB( java.lang.String numCB ) ;

   public java.util.Date getDateExpirCB(  ) ;

   public void setDateExpirCB( java.util.Date dateExpirCB ) ;

   public java.lang.String getCodeSecuCB(  ) ;

   public void setCodeSecuCB( java.lang.String codeSecuCB ) ;

   public java.util.Collection getArticle(  ) ;

   public void setArticle( java.util.Collection article ) ;

   public axlomoso.ezbay.model.interfaces.MembreLocal getMembreLocal(  ) ;

   public void setMembreLocal( axlomoso.ezbay.model.interfaces.MembreLocal membreLocal ) ;

   public axlomoso.ezbay.model.interfaces.VendeurDTO getVendeurDTO(  ) ;

   public java.lang.String updateVendeur( axlomoso.ezbay.model.interfaces.VendeurDTO vendeurDTO ) throws java.lang.Exception;

}
