/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Remote interface for VendeurFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurFacade
   extends javax.ejb.EJBObject
{

   public axlomoso.ezbay.model.interfaces.VendeurDTO createVendeur(  )
      throws java.lang.Exception, java.rmi.RemoteException;

   public void removeVendeur( axlomoso.ezbay.model.interfaces.VendeurDTO vendeurDTO )
      throws java.lang.Exception, java.rmi.RemoteException;

   public axlomoso.ezbay.model.interfaces.VendeurDTO getVendeur( java.lang.String vendeurId )
      throws java.lang.Exception, java.rmi.RemoteException;

   public java.util.Collection getVendeurs(  )
      throws java.rmi.RemoteException;

   public java.util.Collection getArticles( axlomoso.ezbay.model.interfaces.VendeurDTO vendeurDTO )
      throws java.rmi.RemoteException;

}
