/*
 * Generated by XDoclet - Do not edit!
 */
package axlomoso.ezbay.model.interfaces;

/**
 * Local home interface for VendeurFacade.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface VendeurFacadeLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/VendeurFacadeLocal";
   public static final String JNDI_NAME="VendeurFacadeLocal";

   public axlomoso.ezbay.model.interfaces.VendeurFacadeLocal create()
      throws javax.ejb.CreateException;

}
