/*
 * Generated by XDoclet - Do not edit!
 */
package test.helloWorld.interfaces;

/**
 * Local home interface for HelloWorld.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface HelloWorldLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HelloWorldLocal";
   public static final String JNDI_NAME="HelloWorldLocal";

   public test.helloWorld.interfaces.HelloWorldLocal create()
      throws javax.ejb.CreateException;

}
