/*
 * Generated by XDoclet - Do not edit!
 */
package test.helloWorld.interfaces;

/**
 * Remote interface for HelloWorld.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface HelloWorld
   extends javax.ejb.EJBObject
{
   /**
    * An example business method
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public java.lang.String sayHello(  )
      throws java.rmi.RemoteException;

}
